version: 2

build:
  image: latest

python:
  version: 3
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
